/****** Procedure: Creates New StoredProcedure [dbo].[Insert_Data] ******/ CREATE PROCEDURE [dbo].[Insert_Data]
AS

BEGIN
IF EXISTS (SELECT * FROM sys.Tables WHERE name='department') INSERT INTO [dbo].department
VALUES (10, 'Movies', 'Select from a variety of blockbuster movies.'), (20, 'TV Shows', 'All your favotire TV shows are listed here.'),
(30, 'Music', 'The top songs of the 80s, 90s, 2000s and 2010s.'),
(40, 'Games', 'The most exciting games for the top game stations in the world.');
END


BEGIN
IF EXISTS (SELECT * FROM sys.Tables WHERE name='category') INSERT INTO [dbo]. category
VALUES (101, 10, 'Action', 'Action movies description'), (102, 10, 'Drama', 'Drama movies description'),
(103, 10, 'Horror', 'Horror movies description'),
(104, 10, 'Sci-Fi', 'Sci-Fi movies description'), (201, 20, 'Action', 'Action TV shows description'), (202, 20, 'Drama', 'Drama TV shows description'), (203, 20, 'Horror', 'Horror TV shows description'), (204, 20, 'Sci-Fi', 'Sci-Fi TV shows description'), (301, 30, 'Country', 'Country music description'), (302, 30, 'Hip Hop', 'Hip Hop music description'), (303, 30, 'Pop', 'Pop music description'),
(304, 30, 'Rock', 'Rock music description'),
(402, 40, 'PC', 'PC Games description'),
(401, 40, 'Play Station', 'Play Station Games description'), (403, 40, 'Wii', 'Wii Games description'),
(404, 40, 'Xbox', 'Xbox Games description');
END

BEGIN
IF EXISTS (SELECT * FROM sys.Tables WHERE name='category') INSERT INTO [dbo].product
VALUES (10290, 'E.T. the Extra-Terrestrial', '1982 . Fantasy/Science fiction film . 2h 1m', 'After a gentle alien becomes stranded on Earth, the being is discovered and befriended by a young boy named Elliott	(Henry Thomas). Bringing the extraterrestrial into his suburban California house, Elliott introduces E.T., as the alien is dubbed, to his brother and his little sister, Gertie (Drew Barrymore), and the children decide to keep its existence a secret. Soon, however,
E.T. falls ill, resulting in government intervention and a dire situation for both Elliott and the alien.', 'images/products/thumbs/ET.jpg', 'images/products/normal/ET.jpg', 9.99, 9.99, 104, 'Sci- Fi'),

(10323, 'Star Wars', '1977 . Fantasy/Science fiction film . 2h 5m', 'The Imperial Forces -
- under orders from cruel Darth Vader	(David Prowse) -- hold Princess Leia	(Carrie Fisher) hostage, in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker	(Mark Hamill) and Han Solo (Harrison Ford), captain of the Millennium Falcon, work together with the companionable droid duo R2-D2	(Kenny Baker) and C-3PO
(Anthony Daniels) to rescue the beautiful princess, help the Rebel Alliance, and restore freedom and justice to the Galaxy.', 'images/products/thumbs/StarWars.jpg', 'images/products/normal/StarWars.jpg', 19.99, 19.99, 104, 'Sci-Fi'),
(10338, 'The Martian', '2015 . Fantasy/Science fiction film . 2h 31m', 'When astronauts blast off from the planet Mars, they leave behind Mark Watney	(Matt Damon), presumed dead after a fierce storm. With only a meager amount of supplies, the stranded visitor must utilize his wits and spirit to find a way to survive on the hostile planet. Meanwhile, back on Earth, members of NASA and a team of international scientists work tirelessly to bring him home, while his crew mates hatch their own plan for a daring rescue mission.', 'images/products/thumbs/Martian.jpg', 'images/products/normal/Martian.jpg', 19.99, 14.99, 104, 'Sci-Fi'),
(10994, 'Avatar', '2009 . Fantasy/Science fiction film . 2h 42m', 'On the lush alien world of Pandora live the Na''vi, beings who appear primitive but are highly evolved. Because the planet''s environment is poisonous, human/Na''vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. Jake Sully	(Sam Worthington), a paralyzed former Marine, becomes mobile again through one such Avatar and falls in love with a Na''vi woman	(Zoe Saldana). As a bond with her grows, he is drawn into a battle for the survival of her world.', 'images/products/thumbs/Avatar.jpg', 'images/products/normal/Avatar.jpg', 19.99, 19.99, 104, 'Sci-Fi'),
(11002, 'Serenity', '2005 . Fantasy/Fantasy . 1h 59m', 'In this continuation of the television series ''Firefly,'' a group of rebels travels the outskirts of space aboard their ship, Serenity, outside the reach of the Alliance, a sinister regime that controls most of the universe. After the crew takes in Simon	(Sean Maher) and his psychic sister, River	(Summer Glau), whom he has just rescued from Alliance forces, they find themselves being pursued by the Operative	(Chiwetel Ejiofor), an Alliance agent who will stop at nothing to find them.', 'images/products/thumbs/Serenity.jpg', 'images/products/normal/Serenity.jpg', 14.99, 9.99, 104, 'Sci-Fi'),
(11049, 'The Terminator', '1984 . Fantasy/Science fiction film . 1h 48m', 'Disguised as a human, a cyborg assassin known as a Terminator  (Arnold Schwarzenegger) travels from 2029 to 1984 to kill Sarah Connor (Linda Hamilton). Sent to protect Sarah is Kyle Reese
(Michael Biehn), who divulges the coming of Skynet, an artificial intelligence system that will spark a nuclear holocaust. Sarah is targeted because Skynet knows that her unborn son will lead the fight against them. With the virtually unstoppable Terminator in hot pursuit, she and Kyle attempt to escape.', 'images/products/thumbs/Terminator.jpg', 'images/products/normal/Terminator.jpg', 19.99, 4.99, 104, 'Sci-Fi'),
(11121, 'Back to the Future', '1985 . Fantasy/Science fiction film . 2 hours', 'In this 1980s sci-fi classic, small-town California teen Marty McFly	(Michael J. Fox) is thrown back into the ''50s when an experiment by his eccentric scientist friend Doc Brown
(Christopher Lloyd) goes awry. Traveling through time in a modified DeLorean car, Marty encounters young versions of his parents	(Crispin Glover, Lea Thompson), and must make sure that they fall in love or he''ll cease to exist. Even more dauntingly, Marty has to return

to his own time and save the life of Doc Brown.', 'images/products/thumbs/BackToTheFuture.jpg', 'images/products/normal/BackToTheFuture.jpg', 17.99, 17.99, 104, 'Sci-Fi'),
(11549, 'The Avengers', '2012 . Fantasy/Science fiction film . 2h 23m', 'When Thor''s evil brother, Loki	(Tom Hiddleston), gains access to the unlimited power of the energy cube called the Tesseract, Nick Fury	(Samuel L. Jackson), director of S.H.I.E.L.D., initiates a superhero recruitment effort to defeat the unprecedented threat to Earth. Joining Fury''s ''dream team'' are Iron Man	(Robert Downey Jr.), Captain America	(Chris Evans), the Hulk
(Mark Ruffalo), Thor  (Chris Hemsworth), the Black Widow	(Scarlett Johansson) and Hawkeye (Jeremy Renner).', 'images/products/thumbs/Avengers.jpg', 'images/products/normal/Avengers.jpg', 27.99, 27.99, 104, 'Sci-Fi'),
(11889, 'The Fifth Element', '1997 . Fantasy/Science fiction film . 2h 7m', 'In the 23rd century, a New York City cabbie, Korben Dallas	(Bruce Willis), finds the fate of the world in his hands when Leeloo	(Milla Jovovich) falls into his cab. As the embodiment of the fifth element, Leeloo needs to combine with the other four to keep the approaching Great Evil from destroying the world. Together with Father Vito Cornelius (Ian Holm) and zany broadcaster Ruby Rhod	(Chris Tucker), Dallas must race against time and the wicked industrialist Zorg
(Gary Oldman) to save humanity.', 'images/products/thumbs/FifthElement.jpg', 'images/products/normal/FifthElement.jpg', 19.99, 4.99, 104, 'Sci-Fi'),
(12045, 'Edge of Tomorrow', '2014 . Action/Science Fiction . 1h 53m', 'When Earth falls under attack from invincible aliens, no military unit in the world is able to beat them. Maj.
William Cage (Tom Cruise), an officer who has never seen combat, is assigned to a suicide mission. Killed within moments, Cage finds himself thrown into a time loop, in which he relives the same brutal fight -- and his death -- over and over again. However, Cage''s fighting skills improve with each encore, bringing him and a comrade	(Emily Blunt) ever closer to defeating the aliens.', 'images/products/thumbs/EdgeOfTomorrow.jpg', 'images/products/normal/EdgeOfTomorrow.jpg', 24.99, 24.99, 104, 'Sci-Fi'),
(12245, 'The Shining', '1980 . Drama film/Thriller . 2h 40m', 'Jack Torrance	(Jack Nicholson) becomes winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer''s block. He settles in along with his wife, Wendy	(Shelley Duvall), and his son, Danny (Danny Lloyd), who is plagued by psychic premonitions. As Jack''s writing goes nowhere and Danny''s visions become more disturbing, Jack discovers the hotel''s dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.', 'images/products/thumbs/Shining.jpg', 'images/products/normal/Shining.jpg', 14.99, 14.99, 103, 'Horror'),
(13021, 'Psycho', '1960 . Slasher/Thriller . 1h 49m', 'Phoenix secretary Marion Crane (Janet Leigh), on the lam after stealing $40,000 from her employer in order to run away
with her boyfriend, Sam Loomis	(John Gavin), is overcome by exhaustion during a heavy rainstorm. Traveling on the back roads to avoid the police, she stops for the night at the ramshackle Bates Motel and meets the polite but highly strung proprietor Norman Bates
(Anthony Perkins), a young man with an interest in taxidermy and a difficult relationship with his mother.', 'images/products/thumbs/Psycho.jpg', 'images/products/normal/Psycho.jpg', 14.99, 7.49, 103, 'Horror'),
(13295, 'Halloween', '1978 . Slasher/Thriller . 1h 41m', 'On a cold Halloween night in 1963, six year old Michael Myers brutally murdered his 17-year-old sister, Judith. He was sentenced and locked away for 15 years. But on October 30, 1978, while being transferred for a

court date, a 21-year-old Michael Myers steals a car and escapes Smith''s Grove. He returns to his quiet hometown of Haddonfield, Illinois, where he looks for his next victims.', 'images/products/thumbs/Halloween.jpg', 'images/products/normal/Halloween.jpg', 19.99, 9.99,
103, 'Horror'),
(13472, 'The Evil Dead', '1981 . Horror . 1h 25m', 'Ashley ''Ash'' Williams	(Bruce Campbell), his girlfriend and three pals hike into the woods to a cabin for a fun night away.
There they find an old book, the Necronomicon, whose text reawakens the dead when it''s read aloud. The friends inadvertently release a flood of evil and must fight for their lives or become one of the evil dead. Ash watches his friends become possessed, and must make a difficult decision before daybreak to save his own life in this, the first of Sam Raimi''s trilogy.', 'images/products/thumbs/EvilDead.jpg', 'images/products/normal/EvilDead.jpg', 9.99, 9.99, 103, 'Horror'),
(13836, 'Poltergeist', '1982 . Horror . 1h 54m', 'Strange and creepy happenings beset an average California family, the Freelings -- Steve	(Craig T. Nelson), Diane	(JoBeth Williams), teenaged Dana	(Dominique Dunne), eight-year-old Robbie (Oliver Robins), and five-year-old Carol Ann	(Heather O''Rourke) -- when ghosts commune with them through the television set. Initially friendly and playful, the spirits turn unexpectedly menacing, and, when Carol Ann goes missing, Steve and Diane turn to a parapsychologist and eventually an exorcist for help.', 'images/products/thumbs/Poltergeist.jpg', 'images/products/normal/Poltergeist.jpg', 13.99, 13.99, 103, 'Horror'),
(13962, 'Carrie', '1976 . Thriller/Drama . 1h 38m', 'In this chilling adaptation of Stephen King''s horror novel, withdrawn and sensitive teen Carrie White	(Sissy Spacek) faces taunting from classmates at school and abuse from her fanatically pious mother	(Piper Laurie) at home. When strange occurrences start happening around Carrie, she begins to suspect that she has supernatural powers. Invited to the prom by the empathetic Tommy Ross	(William Katt), Carrie tries to let her guard down, but things eventually take a dark and violent turn.', 'images/products/thumbs/Carrie.jpg', 'images/products/normal/Carrie.jpg', 11.99, 11.99, 103, 'Horror'),
(14247, 'The Ring', '2002 . Thriller/Mystery . 2h 25m', 'It sounds like just another urban legend -- a videotape filled with nightmarish images leads to a phone call foretelling the viewer''s death in exactly seven days. Newspaper reporter Rachel Keller	(Naomi Watts) is skeptical of the story until four teenagers all die mysteriously exactly one week after watching just such a tape. Allowing her investigative curiosity to get the better of her, Rachel tracks down the video and watches it. Now she has just seven days to unravel the mystery.', 'images/products/thumbs/TheRing.jpg', 'images/products/normal/TheRing.jpg', 18.99, 18.99,
103, 'Horror'),
(14350, 'A Nightmare on Elm Street', '1984 . Slasher/Indie film . 1h 41m', 'In Wes Craven''s classic slasher film, several Midwestern teenagers fall prey to Freddy Krueger
(Robert Englund), a disfigured midnight mangler who preys on the teenagers in their dreams -- which, in turn, kills them in reality. After investigating the phenomenon, Nancy
(Heather Langenkamp) begins to suspect that a dark secret kept by her and her friends'' parents may be the key to unraveling the mystery, but can Nancy and her boyfriend Glen
(Johnny Depp) solve the puzzle before it''s too late?', 'images/products/thumbs/NightmareOnElmStreet.jpg', 'images/products/normal/NightmareOnElmStreet.jpg', 13.99, 13.99, 103, 'Horror'),

(15819, 'The Conjuring', '2013 . Horror . 1h 52m', 'In 1970, paranormal investigators and demonologists Lorraine   (Vera Farmiga) and Ed	(Patrick Wilson) Warren are summoned to the home of Carolyn	(Lili Taylor) and Roger	(Ron Livingston) Perron. The Perrons and their five daughters have recently moved into a secluded farmhouse, where a supernatural presence has made itself known. Though the manifestations are relatively benign at first, events soon escalate in horrifying fashion, especially after the Warrens discover the house''s macabre history.', 'images/products/thumbs/TheConjuring.jpg', 'images/products/normal/TheConjuring.jpg', 22.99, 22.99, 103, 'Horror'),
(15835, 'Friday the 13th', '1980 . Mystery/Slasher . 1h 35m', 'Crystal Lake''s history of murder doesn''t deter counselors from setting up a summer camp in the woodsy area.
Superstitious locals warn against it, but the fresh-faced young people -- Jack	(Kevin Bacon), Alice  (Adrienne King), Bill (Harry Crosby), Marcie	(Jeannine Taylor) and Ned
(Mark Nelson) -- pay little heed to the old-timers. Then they find themselves stalked by a brutal killer. As they''re slashed, shot and stabbed, the counselors struggle to stay alive against a merciless opponent.', 'images/products/thumbs/FridayThe13th.jpg', 'images/products/normal/FridayThe13th.jpg', 13.99, 4.99, 103, 'Horror'),
(16165, 'Raiders of the Lost Ark', '1981 . Fantasy/Action . 1h 55m', 'Renowned archeologist and expert in the occult, Dr. Indiana Jones, is hired by the U.S. Government to find the Ark of the Covenant, which is believed to still hold the ten commandments. Unfortunately, agents of Hitler are also after the Ark. Indy, and his ex-flame Marion, escape from various close scrapes in a quest that takes them from Nepal to Cairo.', 'images/products/thumbs/RaidersOfArc.jpg', 'images/products/normal/RaidersOfArc.jpg', 9.99,
9.99, 101, 'Action'),
(16534, 'The Bourne Identity', '2002 . Thriller/Drama . 1h 59m', 'The story of a man (Matt Damon), salvaged, near death, from the ocean by an Italian fishing boat. When he
recuperates, the man suffers from total amnesia, without identity or background... except for a range of extraordinary talents in fighting, linguistic skills and self-defense that speak of a dangerous past. He sets out on a desperate search-assisted by the initially rebellious Marie
(Franka Potente) - to discover who he really is, and why he''s being lethally pursued by assassins.', 'images/products/thumbs/BourneIdentity.jpg', 'images/products/normal/BourneIdentity.jpg', 19.99, 19.99, 101, 'Action'),
(16615, 'Die Hard', '1988 . Thriller/Action . 2h 12m', 'New York City policeman John McClane	(Bruce Willis) is visiting his estranged wife (Bonnie Bedelia) and two daughters on Christmas Eve. He joins her at a holiday party in the headquarters of the Japanese-owned business she works for. But the festivities are interrupted by a group of terrorists who take over the exclusive high-rise, and everyone in it. Very soon McClane realizes that there''s no one to save the hostages -- but him.', 'images/products/thumbs/DieHard.jpg', 'images/products/normal/DieHard.jpg', 14.99, 14.99, 101, 'Action'),
(17457, 'Gladiator', '2000 . Drama film/Action . 2h 51m', 'Commodus	(Joaquin Phoenix) takes power and strips rank from Maximus	(Russell Crowe), one of the favored generals of his predecessor and father, Emperor Marcus Aurelius, the great stoical philosopher. Maximus is then relegated to fighting to the death in the gladiator arenas.', 'images/products/thumbs/Gladiator.jpg', 'images/products/normal/Gladiator.jpg', 22.99, 22.99,
101, 'Action'),
(17552, '300', '2006 . Fantasy/Action . 1h 57m', 'In 480 B.C. a state of war exists between Persia, led by King Xerxes (Rodrigo Santoro), and Greece. At the Battle of

Thermopylae, Leonidas	(Gerard Butler), king of the Greek city state of Sparta, leads his badly outnumbered warriors against the massive Persian army. Though certain death awaits the Spartans, their sacrifice inspires all of Greece to unite against their common enemy.', 'images/products/thumbs/300.jpg', 'images/products/normal/300.jpg', 22.99, 22.99, 101, 'Action'),
(17886, 'Point Break', '1991 . Thriller/Sport . 2h 3m', 'After a string of bizarre bank robberies in Southern California, with the crooks donning masks of various former presidents, a federal agent, Johnny Utah	(Keanu Reeves), infiltrates the suspected gang. But this is no ordinary group of robbers. They''re surfers -- led by the charismatic Bodhi (Patrick Swayze) -- who are addicted to the rush of thievery. But when Utah falls in love with a female surfer, Tyler
(Lori Petty), who is close to the gang, it complicates his sense of duty.', 'images/products/thumbs/PointBreak.jpg', 'images/products/normal/PointBreak.jpg', 14.99, 4.99,
101, 'Action'),
(17986, 'Top Gun', '1986 . Drama film/Action . 1h 50m', 'The Top Gun Naval Fighter Weapons School is where the best of the best train to refine their elite flying skills. When hotshot fighter pilot Maverick	(Tom Cruise) is sent to the school, his reckless attitude and cocky demeanor put him at odds with the other pilots, especially the cool and collected Iceman (Val Kilmer). But Maverick isn''t only competing to be the top fighter pilot, he''s also fighting for the attention of his beautiful flight instructor, Charlotte Blackwood	(Kelly McGillis).', 'images/products/thumbs/TopGun.jpg', 'images/products/normal/TopGun.jpg', 19.99, 13.99, 101, 'Action'),
(18215, 'Lethal Weapon', '1987 . Drama film/Thriller . 1h 57m', 'Following the death of his wife, Los Angeles police detective Martin Riggs	(Mel Gibson) becomes reckless and suicidal. When he is reassigned and partnered with Roger Murtaugh	(Danny Glover), Riggs immediately clashes with the older officer. Together they uncover a massive drug- trafficking ring. As they encounter increasingly dangerous situations, Riggs and Murtaugh begin to form a bond. Riggs'' volatile behavior might just help them apprehend the criminals -- if it doesn''t kill them both first.', 'images/products/thumbs/LethalWeapon.jpg', 'images/products/normal/LethalWeapon.jpg', 9.99, 9.99, 101, 'Action'),
(18655, 'Face/Off', '1997 . Thriller/Action . 2h 20m', 'Obsessed with bringing terrorist Castor Troy	(Nicolas Cage) to justice, FBI agent Sean Archer	(John Travolta) tracks down Troy, who has boarded a plane in Los Angeles. After the plane crashes and Troy is severely injured, possibly dead, Archer undergoes surgery to remove his face and replace it with Troy''s. As Archer tries to use his disguise to elicit information about a bomb from Troy''s brother, Troy awakes from a coma and forces the doctor who performed the surgery to give him Archer''s face.', 'images/products/thumbs/FaceOff.jpg', 'images/products/normal/FaceOff.jpg', 14.99, 14.99, 101, 'Action'),
(18719, 'True Lies', '1994 . Thriller/Action . 2h 24m', 'Secretly a spy but thought by his family to be a dull salesman, Harry Tasker	(Arnold Schwarzenegger) is tracking down nuclear missiles in the possession of Islamic jihadist Aziz	(Art Malik). Harry''s mission is complicated when he realizes his neglected wife, Helen	(Jamie Lee Curtis), is contemplating an affair with Simon (Bill Paxton), a used-car salesman who claims he''s a spy. When Aziz kidnaps Harry and Helen, the secret agent must save the world and patch up his marriage at the same time.', 'images/products/thumbs/TrueLies.jpg', 'images/products/normal/TrueLies.jpg', 14.99, 14.99,
101, 'Action'),
(19061, 'The Shawshank Redemption', '1994 . Drama film/Thriller . 2h 22m', 'Andy Dufresne	(Tim Robbins) is sentenced to two consecutive life terms in prison for the

murders of his wife and her lover and is sentenced to a tough prison. However, only Andy knows he didn''t commit the crimes. While there, he forms a friendship with Red (Morgan Freeman), experiences brutality of prison life, adapts, helps the warden, etc., all in 19 years.', 'images/products/thumbs/ShawshankRedemption.jpg', 'images/products/normal/ShawshankRedemption.jpg', 19.99, 19.99, 102, 'Drama'),
(19175, 'Forrest Gump', '1994 . Drama film/Comedy-drama . 2h 22m', 'Slow-witted Forrest Gump (Tom Hanks) has never thought of himself as disadvantaged, and thanks to his supportive mother	(Sally Field), he leads anything but a restricted life. Whether dominating on the gridiron as a college football star, fighting in Vietnam or captaining a shrimp boat, Forrest inspires people with his childlike optimism. But one person Forrest cares about most may be the most difficult to save -- his childhood love, the sweet but troubled Jenny	(Robin Wright).', 'images/products/thumbs/ForrestGump.jpg', 'images/products/normal/ForrestGump.jpg', 19.99,
19.99, 102, 'Drama'),
(19197, 'Titanic', '1997 . Drama film/Disaster Film . 3h 15m', 'James Cameron''s ''Titanic'' is an epic, action-packed romance set against the ill-fated maiden voyage of the R.M.S. Titanic; the pride and joy of the White Star Line and, at the time, the largest moving object ever built. She was the most luxurious liner of her era -- the ''ship of dreams'' -- which ultimately carried over 1,500 people to their death in the ice cold waters of the North Atlantic in the early hours of April 15, 1912.', 'images/products/thumbs/Titanic.jpg',
'images/products/normal/Titanic.jpg', 24.99, 19.99, 102, 'Drama'),
(19425, 'A Beautiful Mind', '2001 . Drama film/Romance . 2h 20m', 'A human drama inspired by events in the life of John Forbes Nash Jr., and in part based on the biography ''A Beautiful Mind'' by Sylvia Nasar. From the heights of notoriety to the depths of depravity, John Forbes Nash Jr. experienced it all. A mathematical genius, he made an astonishing discovery early in his career and stood on the brink of international acclaim. But the handsome and arrogant Nash soon found himself on a painful and harrowing journey of self-discovery.', 'images/products/thumbs/BeautifulMind.jpg', 'images/products/normal/BeautifulMind.jpg', 17.99, 17.99, 102, 'Drama'),
(19497, 'Goodfellas', '1990 . Crime film/Drama film . 2h 28m', 'A young man grows up in the mob and works very hard to advance himself through the ranks. He enjoys his life of money and luxury, but is oblivious to the horror that he causes. A drug addiction and a few mistakes ultimately unravel his climb to the top. Based on the book ''Wiseguy'' by Nicholas Pileggi.', 'images/products/thumbs/Goodfellas.jpg', 'images/products/normal/Goodfellas.jpg', 19.99, 19.99, 102, 'Drama'),
(19634, 'Good Will Hunting', '1997 . Drama film/Indie film . 2h 6m', 'Will Hunting (Matt Damon) has a genius-level IQ but chooses to work as a janitor at MIT. When he
solves a difficult graduate-level math problem, his talents are discovered by Professor Gerald Lambeau	(Stellan Skarsgard), who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he will get treatment from therapist Sean Maguire	(Robin Williams).', 'images/products/thumbs/GoodWillHunting.jpg', 'images/products/normal/GoodWillHunting.jpg', 19.99, 11.99, 102, 'Drama'),
(19938, 'The Green Mile', '1999 . Fantasy/Crime film . 3h 9m', 'Paul Edgecomb (Tom Hanks) walked the mile with a variety of cons. He had never encountered someone like John Coffey	(Michael Clarke Duncan), a massive black man convicted of brutally killing a pair of young sisters. Coffey had the size and strength to kill anyone, but not the demeanor. Beyond

his simple, naive nature and a deathly fear of the dark, Coffey seemed to possess a prodigious, supernatural gift. Paul began to question whether Coffey was truly guilty of murdering the two girls.', 'images/products/thumbs/GreenMile.jpg', 'images/products/normal/GreenMile.jpg', 23.99, 23.99, 102, 'Drama'),
(20028, 'Rain Man', '1988 . Drama film/Melodrama . 2h 13m', 'When car dealer Charlie Babbitt	(Tom Cruise) learns that his estranged father has died, he returns home to Cincinnati, where he discovers that he has an autistic older brother named Raymond	(Dustin Hoffman) and that his father''s $3 million fortune is being left to the mental institution in which Raymond lives. Motivated by his father''s money, Charlie checks Raymond out of the facility in order to return with him to Los Angeles. The brothers'' cross-country trip ends up changing both their lives.', 'images/products/thumbs/RainMan.jpg', 'images/products/normal/RainMan.jpg', 9.99, 9.99, 102, 'Drama'),
(20386, 'Cast Away', '2000 . Drama film/Adventure . 2h 23m', 'Obsessively punctual FedEx executive Chuck Noland	(Tom Hanks) is en route to an assignment in Malaysia when his plane crashes over the Pacific Ocean during a storm. The sole survivor of the flight, Chuck washes ashore on a deserted island. When his efforts to sail away and contact help fail, Chuck learns how to survive on the island, where he remains for years, accompanied by only his handmade volleyball friend, Wilson. Will Chuck ever return to civilization and reunite with his loved ones?', 'images/products/thumbs/CastAway.jpg', 'images/products/normal/CastAway.jpg', 14.99, 4.99, 102, 'Drama'),
(20611, 'The Color Purple', '1985 . Drama film/Historical period drama . 2h 34m', 'An epic tale spanning forty years in the life of Celie	(Whoopi Goldberg), an African-American woman living in the South who survives incredible abuse and bigotry. After Celie''s abusive father marries her off to the equally debasing ''Mister'' Albert Johnson	(Danny Glover), things go from bad to worse, leaving Celie to find companionship anywhere she can. She perseveres, holding on to her dream of one day being reunited with her sister in Africa. Based on the novel by Alice Walker.', 'images/products/thumbs/ColorPurple.jpg', 'images/products/normal/ColorPurple.jpg', 19.99, 19.99, 102, 'Drama'),
(21399, 'Battlestar Galactica', '2004-2009 Sci-Fi TV Series', 'This update of the late- 1970s series takes a decidedly darker tone as what''s left of humankind struggles for survival against the robot Cylons, who have killed millions. The Galactica, led by William Adama, protects a patched-together fleet of civilians -- led by de facto president Laura Roslin -- in search of a mythical planet called Earth.', 'images/products/thumbs/BSGallactica.jpg', 'images/products/normal/BSGallactica.jpg', 49.99, 49.99, 204, 'Sci-Fi'),
(21530, 'Stargate SG-1', '1997-2007 Sci-Fi TV Series', 'A team of explorers made up of soldiers and scientists travels through a Stargate, an ancient portal to other planets. They use the Stargate to explore new worlds, forge ties with friendly civilizations and protect Earth from hostile forces. The TV series is based on the theatrical film ''Stargate.''', 'images/products/thumbs/SG1.jpg', 'images/products/normal/SG1.jpg', 79.99, 69.99, 204, 'Sci- Fi'),
(21917, 'Stargate Atlantis', '2004-2009 Sci-Fi TV Series', 'Within the ruins of the legendary city of Atlantis is buried a secret base left by the Ancients, originators of the Stargate. A new team of explorers travels to the distant galaxy where Atlantis is located, where a primitive human civilization is threatened by a sinister enemy.', 'images/products/thumbs/SGAtlantis.jpg', 'images/products/normal/SGAtlantis.jpg', 59.99, 59.99, 204, 'Sci-Fi'),

(21966, 'Farscape', '1999-2003 Sci-Fi TV Series', 'American astronaut John Crichton finds himself thrown across the universe when an experimental mission goes bad. Crichton teams up with a group of rebels involved in an intergalactic battle and begins a journey unlike anything he dreamed was possible while trying to find a way back to Earth.', 'images/products/thumbs/Farscape.jpg', 'images/products/normal/Farscape.jpg', 39.99, 29.99,
204, 'Sci-Fi'),
(22530, 'Caprica', '2010 Sci-Fi TV Series', 'Set nearly 60 years before the popular ''Battlestar Galactica'' series, this prequel traces the progress of two prominent families, the Greystones and the Adamas, in the peaceful world of the 12 Colonies. An act of terrorism has tragic consequences for both families, which shapes the future of the battle for humanity.', 'images/products/thumbs/Caprica.jpg', 'images/products/normal/Caprica.jpg', 19.99, 19.99, 204, 'Sci-Fi'),
(22577, 'Stargate Universe', '2009-2011 Sci-Fi TV Series', 'Led by the brilliant scientist Dr. Nicholas Rush, a band of civilians and soldiers faces a whole new world -- and fights for survival -- after their secret military base is attacked. The survivors emerge aboard an ancient ship, unable to return to Earth and now on a course to parts unknown. Amid the darkness the group must meet its most basic needs of food, water and air while discovering the secrets of the ship''s Stargate to ultimately survive.', 'images/products/thumbs/SGUniverse.jpg', 'images/products/normal/SGUniverse.jpg', 19.99, 19.99, 204, 'Sci-Fi'),
(22624, 'Continuum', '2012-2015 Sci-Fi TV Series', 'Detective Kiera Cameron is a cop from the year 2077 who was raised to rely on technology more than anything else, even herself. Now she and a group of deadly criminals called Liber8 are trapped in present-day Vancouver. Cameron needs to stop Liber8 before it can take down the corporations which will one day rule the world -- thus altering the course of the future and changing the 2077 that Cameron calls home. She enlists the help of a teenage tech genius named Alec Sadler to help figure out a way to get her back to her own time, and she manages to work with the Vancouver Police Department with Detective Carlos Fonnegra to keep an eye on Liber8. With different ideals and backgrounds, Cameron and Fonnegra clash, but they trust each other, and Cameron is slowly learning to trust herself as well.', 'images/products/thumbs/Continuum.jpg', 'images/products/normal/Continuum.jpg', 34.49, 34.49, 204, 'Sci-Fi'),
(22933, 'Fringe', '2008-2013 Sci-Fi TV Series', 'FBI Special Agent Olivia Dunham is assigned to the bureau''s Fringe Division, in which she investigates unusual crimes and occurrences. Assisting Olivia in her investigations are once-institutionalized scientist Dr. Walter Bishop, his jack-of-all-trades son, Peter, and FBI Junior Agent Astrid Farnsworth. As the team investigates cases of science gone awry, they discover connections to their own past and to a parallel universe. As the team solves cases in these interconnected worlds, new discoveries and complications continue to arise.', 'images/products/thumbs/Fringe.jpg', 'images/products/normal/Fringe.jpg', 54.99, 39.99, 204, 'Sci-Fi'),
(23100, 'Doctor Who', '2005-2017 Sci-Fi TV Series', 'Doctor Who is a classic science- fiction series with a cult following. The Doctor is called a ''Time Lord,'' a time-traveling scientist from a far off planet, who travels through time and space in a shop known by the acronym TARDIS. A TARDIS is a machine that is larger on the inside than the outside and is supposed to change its appearance based on its surroundings. The Doctor is also able to evolve his biology, so he appears as many different people throughout the series. The Doctor loves Earth, so he makes many trips here to save the planet, or to enlist earthlings to help him with tasks in the

galaxy.', 'images/products/thumbs/DoctorWho.jpg', 'images/products/normal/DoctorWho.jpg', 69.99, 69.99, 204, 'Sci-Fi'),
(23215, 'Firefly', '2002-2003 Sci-Fi TV Series', 'Set 500 years in the future after a universal civil war, the crew of a small transport spaceship takes any job so long as it puts food on the table. The disparate men and women just want to survive and maybe have better lives, but they face constant challenges on the new frontier, such as the Reavers -- flesh-eating mongrels who live on the fringes of the universe.', 'images/products/thumbs/Firefly.jpg', 'images/products/normal/Firefly.jpg', 29.99, 29.99, 204, 'Sci-Fi'),
(23473, 'Sons of Anarchy', 'American drama series', 'Single father Jax Teller finds his loyalty to his outlaw motorcycle club tested by his growing unease concerning the group''s lawlessness. While the club protects and patrols the town of Charming, Calif., keeping drug dealers away, its activities also include a thriving -- and lucrative -- illegal arms business.', 'images/products/thumbs/SOA.jpg', 'images/products/normal/SOA.jpg', 49.99, 49.99, 202, 'Drama'),
(23718, 'Game of Thrones', 'American drama series', 'George R.R. Martin''s best-selling book series ''A Song of Ice and Fire'' is brought to the screen as HBO sinks its considerable storytelling teeth into the medieval fantasy epic. It''s the depiction of two powerful families -- kings and queens, knights and renegades, liars and honest men -- playing a deadly game for control of the Seven Kingdoms of Westeros, and to sit atop the Iron Throne. Martin is credited as a co-executive producer and one of the writers for the series, which was filmed in Northern Ireland and Malta.', 'images/products/thumbs/GOT.jpg', 'images/products/normal/GOT.jpg', 99.99, 79.99, 202, 'Drama'),
(23834, 'Breaking Bad', 'American drama series', 'Mild-mannered high school chemistry teacher Walter White thinks his life can''t get much worse. His salary barely makes ends meet, a situation not likely to improve once his pregnant wife gives birth, and their teenage son is battling cerebral palsy. But Walter is dumbstruck when he learns he has terminal cancer.
Realizing that his illness probably will ruin his family financially, Walter makes a desperate bid to earn as much money as he can in the time he has left by turning an old RV into a meth lab on wheels.', 'images/products/thumbs/BreakingBad.jpg', 'images/products/normal/BreakingBad.jpg', 49.99, 49.99, 202, 'Drama'),
(24735, 'The X-Files', 'Drama series', 'In one of the longest-running science fiction series in network TV history, FBI special agents investigate unexplained, mind-bending cases known as ''X-Files.'' Though the government is convinced that the outlandish reports are false, conspiracy theorist Fox Mulder	(David Duchovny) and realist Dana Scully	(Gillian Anderson), for most of the series, stop at nothing to prove that ''the truth is out there.'' Series creator Chris Carter also serves as executive producer of the thrilling pop-culture phenomenon.', 'images/products/thumbs/XFiles.jpg', 'images/products/normal/XFiles.jpg', 19.99, 19.99, 202, 'Drama'),
(24907, 'Boardwalk Empire', 'American drama series', 'Atlantic City at the dawn of Prohibition is a place where the rules don''t apply. And the man who runs things -- legally and otherwise -- is the town''s treasurer, Enoch ''Nucky'' Thompson, who is equal parts politician and gangster. Side by side with his brother Elias, Atlantic City''s sheriff, and a crew of ward bosses and local tough guys, Nucky gains a reputation as the man to see for illegal alcohol. He does business with all the top gangsters -- Al Capone, Lucky Luciano, ''Big Jim'' Colosimo -- and he does it well ... until a former protégé takes matters into his own hands, setting the Feds on

Nucky''s tail.', 'images/products/thumbs/BoardWalkEmpire.jpg', 'images/products/normal/BoardWalkEmpire.jpg', 49.99, 49.99, 202, 'Drama'),
(25117, 'Better Call Saul', 'American drama series', 'He wasn''t always Saul Goodman, ace attorney for chemist-turned-meth dealer Walter White. Six years before he begins to represent Albuquerque''s most notorious criminal, Goodman is Jimmy McGill, a small-time attorney hustling to make a name for himself. He''s a forceful champion for his low-income clients, an underdog whose morals and ambitions often clash. Jimmy works with private eye Mike Ehrmantraut, a former Philadelphia cop and recent transplant to the Southwest. Mike has a specialized skill set -- he''s a ''fixer'' of sticky situations -- that Jimmy soon learns to appreciate.', 'images/products/thumbs/Saul.jpg', 'images/products/normal/Saul.jpg', 19.99, 14.99, 202, 'Drama'),
(26003, 'Mr. Robot', 'American drama series', 'Young, anti-social computer programmer Elliot works as a cybersecurity engineer during the day, but at night he is a vigilante hacker. He is recruited by the mysterious leader of an underground group of hackers to join their organization. Elliot''s task? Help bring down corporate America, including the company he is paid to protect, which presents him with a moral dilemma. Although he works for a corporation, his personal beliefs make it hard to resist the urge to take down the heads of multinational companies that he believes are running -- and ruining -- the world.', 'images/products/thumbs/MrRobot.jpg', 'images/products/normal/MrRobot.jpg', 29.99, 29.99,
202, 'Drama'),
(26073, 'Orphan Black', 'Canadian television series', 'Sarah is a street-wise woman with a troubled past as an English orphan who bounced around foster homes before being taken in by Mrs. S, who uprooted her and her foster brother, Felix, to North America. She has made bad decisions in her life but always strives to do right by daughter Kira. When Sarah witnesses the suicide of a woman, Beth	(who looks like her) she decides to steal Beth''s identity -- boyfriend and money included -- in an attempt to begin a new life for herself and Kira, with whom Sarah hopes to reunite. But assuming Beth''s life -- Sarah eventually learns that Beth was her clone -- doesn''t go as smoothly as she anticipates because Beth was a cop caught in the middle of a deadly conspiracy, making Sarah the new target. Sarah must fight to stay alive while trying to escape from the complex web. As more threads appear, Sarah is pulled deeper, and Felix becomes her one true confidant.', 'images/products/thumbs/OrphanBlack.jpg', 'images/products/normal/OrphanBlack.jpg', 19.99, 15.99, 202, 'Drama'),
(26852, 'Justified', 'American drama series', 'Deputy Raylan Givens has his own, Wild West-style methods of upholding justice, putting him at odds with the criminals he hunts and with his bosses in the U.S. Marshals Service. And an incident prompts his reassignment to the Kentucky district where he grew up. The character is based on one created by author Elmore Leonard in several books and short stories.', 'images/products/thumbs/Justified.jpg', 'images/products/normal/Justified.jpg', 34.99, 34.99, 202, 'Drama'),
(27103, 'Deadwood', 'American television series', 'Deadwood is set in a mining town that was not part of any U.S. state or territory in the post-Civil War years, and thus was literally lawless. Deadwood attracts people looking to get rich after a huge gold strike, as well as those looking to capitalize on the lack of organized law in the town, built on land stolen from the Sioux.', 'images/products/thumbs/Deadwood.jpg', 'images/products/normal/Deadwood.jpg', 39.99, 39.99, 202, 'Drama'),
(27226, 'Prison Break', 'American television series', 'Michael Scofield is a desperate man in a desperate situation. His brother, Lincoln Burrows, was convicted of a crime he didn''t

commit and put on Death Row. Michael holds up a bank to get himself incarcerated alongside his brother in Fox River State Penitentiary, then sets in motion a series of elaborate plans to break Lincoln out and prove his innocence. Once out of jail, their perils aren''t over -- the brothers must flee to escape recapture and battle an intricate political conspiracy that puts everyone''s life at risk.', 'images/products/thumbs/PrisonBreak.jpg', 'images/products/normal/PrisonBreak.jpg', 37.99, 37.99, 201, 'Action'),
(27344, 'Spartacus: Blood and Sand', 'American television series', 'Torn from his homeland and separated from the woman he loves, Spartacus is forced into slavery and condemned to the bloody gladiator''s arena in Rome. As he navigates the violent and brutal world he realizes that not all battles are fought in the arena, and that he must overcome treachery and temptation to survive. This retelling of the story of Spartacus is rife with blood, violence and sex, set to the sounds of jarring guitars, so it''s definitely not for the younger crowd.', 'images/products/thumbs/Spartacus.jpg', 'images/products/normal/Spartacus.jpg', 24.99, 24.99,
201, 'Action'),
(27752, 'Dexter', 'American television series', 'Dexter Morgan is a Miami-based blood splatter expert who doesn''t just solve murders; he commits them too. In fact, he''s a serial killer -
- but he only murders the guilty, so he feels justified with his lifestyle choices. His policewoman sister and his cop co-workers have no idea Dexter lives a double life; however, adoptive father Harry knows his secret, and does, in fact, help Dexter hone his ''skills.'' It''s a unique brand of justice for which charming Dexter feels a psychological hunger.', 'images/products/thumbs/Dexter.jpg', 'images/products/normal/Dexter.jpg', 39.99, 39.99, 201, 'Action'),
(27770, 'Agents of S.H.I.E.L.D.', 'American television series', 'Phil Coulson	(Clark Gregg, reprising his role from ''The Avengers'' and ''Iron Man'' ) heads an elite team of fellow agents with the worldwide law-enforcement organization known as SHIELD	(Strategic Homeland Intervention Enforcement and Logistics Division), as they investigate strange occurrences around the globe. Its members -- each of whom brings a specialty to the group -- work with Coulson to protect those who cannot protect themselves from extraordinary and inconceivable threats, including a formidable group known as Hydra.', 'images/products/thumbs/SHIELD.jpg', 'images/products/normal/SHIELD.jpg', 29.99, 29.99,
201, 'Action'),
(28239, '24', 'American television series', 'Counterterrorism agent Jack Bauer fights the bad guys of the world, a day at a time. With each week''s episode unfolding in real time, ''24'' covers a single day in the life of Bauer each season. Jack deals with assassination attempts, nuclear attacks, bioterrorism, torture, traitors, sleeper cells, other bad guys and the alarming tendency for his romances to end badly -- very badly.', 'images/products/thumbs/24.jpg', 'images/products/normal/24.jpg', 49.99, 34.99, 201, 'Action'),
(28700, 'Lost', 'American television series', 'The survivors of Oceanic Flight 815 were 1,000 miles off course when they crashed on a lush, mysterious island. Each person possesses a shocking secret, but they''ve got nothing on the island itself, which harbors a monstrous security system, a series of underground bunkers and a group of violent survivalists hidden in the shadows.', 'images/products/thumbs/Lost.jpg', 'images/products/normal/Lost.jpg', 29.99, 29.99,
201, 'Action'),
(29730, 'Vikings', 'Canadian-Irish television series', 'Viking Ragnar Lothbrok is a young farmer and family man who is frustrated by the policies of Earl Haraldson, his local chieftain who sends his Viking raiders east to the Baltic states and Russia, whose residents are as poor as

the Norsemen. Ragnar wants to head west, across the ocean, to discover new civilizations. With assistance from his friend Floki, Ragnar builds a faster, sleeker fleet of boats to help him make it to the Western world. Through the years Ragnar, who claims to be a direct descendant of the god Odin, continues to struggle with Earl until the two face each other in a final battle for supremacy. Following that, Ragnar goes on a search for new lands to conquer.', 'images/products/thumbs/Vikings.jpg', 'images/products/normal/Vikings.jpg', 29.99, 29.99, 201, 'Action'),
(29798, 'Black Sails', 'Television Series', 'A prequel to the classic Robert Louis Stevenson novel ''Treasure Island,'' ''Black Sails'' is a pirate adventure that centers on the tales of Captain Flint, who has a reputation throughout the West Indies as being the most brilliant, most feared of all the Golden Age pirates. It''s 1715, and as Flint fights for the survival of New Providence Island -- a debauched paradise teeming with pirates, prostitutes, thieves and fortune seekers -- in the wake of threats from British and Spanish forces, he aligns himself with Eleanor Guthrie, daughter of the local kingpin, to hunt the ultimate prize and ensure his people''s survival. But standing in the way are rival captains, Eleanor''s intrusive father, and perhaps the bigger obstacle of all: John Silver, a young, fast-talking, authority-flouting sailor recently added to Flint''s crew.', 'images/products/thumbs/BlackSails.jpg', 'images/products/normal/BlackSails.jpg', 29.99, 29.99,
201, 'Action'),
(30008, 'MacGyver', 'Television Series', 'MacGyver is a top agent for the Phoenix Foundation, a progressive agency devoted to righting the wrongs of the world. Even more progressive is the genius MacGyver, who never carries a gun and always thwarts the enemy with vast scientific knowledge - sometimes with little more than a paper clip and the duct tape in his pocket.', 'images/products/thumbs/MacGyver.jpg', 'images/products/normal/MacGyver.jpg', 39.99, 19.99, 201, 'Action'),
(30043, 'The Walking Dead', 'American television series', 'Based on the comic book series written by Robert Kirkman, this gritty drama portrays life in the weeks and months following a zombie apocalypse. Led by police officer Rick Grimes, his family and a group of other survivors find themselves constantly on the move in search of a safe and secure home. But the pressure each day to stay alive sends many in the group to the deepest depths of human cruelty, and Rick discovers that the overwhelming fear of the survivors can be more deadly than the zombies walking among them.', 'images/products/thumbs/WalkingDead.jpg', 'images/products/normal/WalkingDead.jpg', 44.99, 44.99, 201, 'Action'),
(30356, 'American Horror Story', 'American television series', 'American Horror Story was created by the co-creators of ''Glee,'' but the shows have little in common besides that. The show revolves around the Harmons, a family of three, who move from Boston to Los Angeles in order to reconcile past anguish. What the Harmons don''t know is that the house they''ve moved into is haunted. But it''s not haunted by Casperesque friendly ghosts -- it''s haunted by demonic creatures. The creatures have a history of not only spooking the house''s residents but also devouring them. After living in this house, family patriarch and psychiatrist, Ben, may need a shrink of his own.', 'images/products/thumbs/AmericanHorrorStory.jpg', 'images/products/normal/AmericanHorrorStory.jpg', 29.99, 29.99, 203, 'Horror'),
(30766, 'The Twilight Zone', 'American television series', 'The Twilight Zone was the brainchild of Emmy Award-winner Rod Serling, who served as host and wrote over 80 episodes of the original show''s 150-plus episode run. It''s a strange mix of horror, science-fiction, drama, comedy and superstition. Serling introduced each episode, and many of the black and white hours concluded with a surprise ending. Actors such as Burt Reynolds, Roddy McDowell and

Robert Redford made appearances in some of the more well-known stories.', 'images/products/thumbs/TwilightZone.jpg', 'images/products/normal/TwilightZone.jpg', 19.99,
14.99, 203, 'Horror'),
(31029, 'Tales from the Crypt', 'American television series', 'Based on the EC Comics series of the same name, this campy and stylized anthology series recounts a string of horrific yarns introduced by the show''s moldering host, the Crypt Keeper. Episodes feature a number of well-known actors and actresses, including Dan Aykroyd, Malcolm McDowell, Christopher Reeve and Sam Waterston. Michael J. Fox, Tom Hanks, Robert Zemeckis, Richard Donner and John Frankenheimer are among notables who directed episodes.', 'images/products/thumbs/TalesFromTheCrypt.jpg', 'images/products/normal/TalesFromTheCrypt.jpg', 19.99, 9.99, 203, 'Horror'),
(31170, 'The Strain', 'American television series', 'Dr. Ephraim Goodweather, the head of the CDC''s New York-based Canary Project, is called upon to investigate when an airplane lands with everybody on board dead. What his team discovers is a viral outbreak that has similarities to an ancient strain of vampirism. As the virus begins to spread, Goodweather works with his team and a group of the city''s residents to wage a war that could hold humanity''s fate in its hand. The show''s executive producers include Oscar-nominated writer Guillermo del Toro and Emmy- winning producer Carlton Cuse.', 'images/products/thumbs/TheStrain.jpg', 'images/products/normal/TheStrain.jpg', 39.99, 39.99, 203, 'Horror'),
(31300, 'Penny Dreadful', 'American-British drama series', 'Many people are familiar with classic literary characters like Dr. Frankenstein and Dorian Gray. ''Penny Dreadful'' brings those and other characters into a new light by exploring their origin stories in this psychological thriller that takes place in the dark corners of Victorian London. Sir Malcolm is an explorer who has lost his daughter to the city''s creatures, and he will do whatever is needed to get her back and to right past wrongs. His accomplice, seductive clairvoyant Vanessa Ives, recruits charming American Ethan Chandler to help locate Sir Malcolm''s daughter and slay some monsters. Oscar-winner Sam Mendes (''American Beauty'') is one of the series'' executive producers.', 'images/products/thumbs/PennyDreadful.jpg', 'images/products/normal/PennyDreadful.jpg', 29.99, 29.99, 203, 'Horror'),
(31402, 'Bates Motel', 'American television series', 'After the death of her husband, Norma Bates buys a motel in the picturesque coastal town of White Pine Bay, giving herself and teenage son Norman a chance to begin anew. Shy Norman is reluctant at first, but with the help of his mother -- with whom he shares an intensely close relationship -- the boy begins to open up to others and make new friends. Some locals, however, aren''t as friendly and welcoming to the Bates, who discover that because White Pine Bay isn''t as peaceful as it appears, they are forced to do whatever it takes to survive. The drama series, from executive producers Carlton Cuse
(''Lost'') and Kerry Ehrin	(''Friday Night Lights'') and inspired by the seminal 1960 horror film ''Psycho,'' explores the formative years of Norman Bates and how his complicated bond with his mother forged a serial killer.', 'images/products/thumbs/BatesMotel.jpg', 'images/products/normal/BatesMotel.jpg', 29.99, 29.99, 203, 'Horror'),
(31733, 'Hannibal', 'American television series', 'Gifted criminal profiler Will Graham has a unique way of thinking that allows him to empathize with anyone, including psychopaths. But while helping the FBI pursue a particularly complicated serial killer, he decides he could use some help and enlists the brilliant psychiatrist Hannibal Lecter. The two form a partnership and it seems that there is no villain they can''t catch together, but Lecter harbors a dark secret. His own brilliant mind has gone to the dark side and he has more in common with the criminals they hunt

than Will could possibly imagine.', 'images/products/thumbs/Hannibal.jpg', 'images/products/normal/Hannibal.jpg', 29.99, 29.99, 203, 'Horror'),
(32010, 'Masters of Horror', 'Television Series', 'Hourlong horror films from famous directors are showcased in this anthology series, with works by Dario Argento, John Carpenter, Larry Cohen, Don Coscarelli, Joe Dante, Mick Garris, Stuart Gordon, Tobe Hooper, John Landis, William Malone, Lucky McKee, John McNaughton and Takashi Miike.', 'images/products/thumbs/MastersOfHorror.jpg', 'images/products/normal/MastersOfHorror.jpg', 24.99, 24.99, 203, 'Horror'),
(32881, 'Tales from the Darkside', 'American TV series', 'A ''Twilight Zone'' type of show, this horror anthology series, produced by noted horror filmmaker George A. Romero, explores the macabre, but like its predecessor, always with a twist. Low budget but with a huge cult following, the show explores horror and supernatural story lines and guest-stars several veteran actors. Many ''Tales From the Darkside'' episodes are adapted from stories written by well-known authors, including Stephen King, Harlan Ellison, Clive Barker and John Cheever. This series was followed by a feature film, ''Tales From the Darkside: The Movie.''', 'images/products/thumbs/TalesFromTheDarkside.jpg', 'images/products/normal/TalesFromTheDarkside.jpg', 24.99, 19.99, 203, 'Horror'),
(33033, 'Alfred Hitchcock Presents', 'American television series', 'The familiar ''plink, plink'' of the theme song, accompanied by the line drawing of a man in profile immediately identifies the show as ''Alfred Hitchcock Presents.'' The famed director opens almost every episode with the words ''Good evening ...'' After a joke -- usually about the evening''s sponsor -- Hitchcock lays the groundwork for that episode''s freestanding story of suspense and terror.', 'images/products/thumbs/Hitchcock.jpg', 'images/products/normal/Hitchcock.jpg', 19.99, 19.99,
203, 'Horror'),
(33153, 'Carrie Underwood - Storyteller', 'Studio album by Carrie Underwood', 'Storyteller is the fifth studio album recorded by American singer and songwriter Carrie Underwood. It was released on October 23, 2015, through Sony Music Entertainment.', 'images/products/thumbs/CarrieUnderwoodStoryteller.jpg', 'images/products/normal/CarrieUnderwoodStoryteller.jpg', 9.89, 9.89, 301, 'Country'),
(33256, 'Blake Shelton - If I''m Honest', 'Studio album by Blake Shelton', 'If I''m Honest is the tenth studio album by American country music singer Blake Shelton. The album was released on May 20, 2016, by Warner Bros. Nashville.', 'images/products/thumbs/BlakeSheltonHonest.jpg', 'images/products/normal/BlakeSheltonHonest.jpg', 11.99, 11.99, 301, 'Country'),
(33854, 'Toby Keith - 35 Biggest Hits', 'Album by Toby Keith', '35 Biggest Hits is a two- disc greatest hits album from American country music artist Toby Keith. It was released on May 6, 2008.', 'images/products/thumbs/TobyKeithHits.jpg',
'images/products/normal/TobyKeithHits.jpg', 8.49, 8.49, 301, 'Country'),
(33903, 'Reba McEntire - Love Somebody', 'Studio album by Reba McEntire', 'Love Somebody is the twenty-seventh studio album from American country music singer Reba McEntire. The album was released on April 14, 2015, by Nash Icon. This is McEntire''s first studio album since the 2010 release of All the Women I Am.', 'images/products/thumbs/RebaLoveSomebody.jpg', 'images/products/normal/RebaLoveSomebody.jpg', 8.99, 4.99, 301, 'Country'),
(33977, 'Kenny Chesney - The Big Revival', 'Studio album by Kenny Chesney', 'The Big Revival is the sixteenth studio album by American country music artist Kenny Chesney, released

by Blue Chair and Columbia Records on September 23, 2014.', 'images/products/thumbs/KennyChesneyRevival.jpg', 'images/products/normal/KennyChesneyRevival.jpg', 6.99, 6.99, 301, 'Country'),
(34047, 'Garth Brooks - Man Against Machine', 'Studio album by Garth Brooks', 'Man Against Machine is the ninth studio album by American country pop artist Garth Brooks. It was released on November 11, 2014 by RCA Records Nashville and Pearl Records.', 'images/products/thumbs/GarthBrooksMachine.jpg', 'images/products/normal/GarthBrooksMachine.jpg', 6.49, 4.45, 301, 'Country'),
(34170, 'The Essential Johnny Cash', 'Compilation album by Johnny Cash', 'The Essential Johnny Cash is a double-compact disc compilation by Johnny Cash released as part of Sony BMG''s Essential series. It was compiled to commemorate Cash''s 70th birthday.', 'images/products/thumbs/JohnnyCashEssential.jpg', 'images/products/normal/JohnnyCashEssential.jpg', 11.99, 9.99, 301, 'Country'),
(34702, 'Darius Rucker - Southern Style', 'Studio album by Darius Rucker', 'Southern Style is the fifth studio album and fourth in the country genre by American country music artist Darius Rucker. It was released on March 31, 2015, by Capitol Records Nashville.', 'images/products/thumbs/DariusRuckerSouthernStyle.jpg', 'images/products/normal/DariusRuckerSouthernStyle.jpg', 9.99, 9.99, 301, 'Country'),
(34937, 'George Strait - 50 Number Ones', 'Compilation album by George Strait', '50 Number Ones is a compilation album, released in 2004, by American country music singer George Strait.', 'images/products/thumbs/GeorgeStraitHits.jpg', 'images/products/normal/GeorgeStraitHits.jpg', 9.99, 6.48, 301, 'Country'),
(35102, 'Hank Williams, Jr.''s Greatest Hits', 'Compilation album by Hank Williams Jr.', 'Hank Williams Jr.''s Greatest Hits is a compilation album by American country music artist Hank Williams Jr.', 'images/products/thumbs/HankWilliamsJrHits.jpg', 'images/products/normal/HankWilliamsJrHits.jpg', 7.99, 7.99, 301, 'Country'),
(35494, 'De La Soul - 3 Feet High and Rising', 'Studio album by De La Soul', '3 Feet High and Rising is the debut studio album by the American hip hop trio De La Soul. It was released on March 14, 1989, by Tommy Boy Records and Warner Bros. Records.', 'images/products/thumbs/DeLaSoulRising.jpg', 'images/products/normal/DeLaSoulRising.jpg', 4.99, 4.99, 302, 'Hip-Hop'),
(35839, 'Beastie Boys - Licensed to Ill', 'Studio album by Beastie Boys', 'Licensed to Ill is the debut studio album by the American hip hop group Beastie Boys. It was released on November 15, 1986 by Def Jam and Columbia Records. It was the first rap LP to top the Billboard album chart.', 'images/products/thumbs/BeastieBoysIll.jpg', 'images/products/normal/BeastieBoysIll.jpg', 5.48, 5.48, 302, 'Hip-Hop'),
(35859, 'Eminem - The Marshall Mathers LP', 'Studio album by Eminem', 'The Marshall Mathers LP is the third studio album by American rapper Eminem. It was released on May 23, 2000, by Aftermath Entertainment, Interscope Records, and Eminem''s newly founded label, Shady Records.', 'images/products/thumbs/EminemMarshallMathers.jpg', 'images/products/normal/EminemMarshallMathers.jpg', 9.99, 8.5, 302, 'Hip-Hop'),
(36247, 'Enter the Wu-Tang (36 Chambers)', 'Studio album by Wu-Tang Clan', 'Enter the Wu-Tang (36 Chambers) is the debut studio album by the American hip hop group Wu- Tang Clan, released November 9, 1993, on Loud Records and distributed through RCA Records.', 'images/products/thumbs/EnterTheWu.jpg', 'images/products/normal/EnterTheWu.jpg', 6.99, 6.99, 302, 'Hip-Hop'),

(36410, '2Pac - All Eyez on Me', 'Studio album by Tupac Shakur', 'All Eyez on Me is the fourth studio album by American rapper 2Pac, released on February 13, 1996 under Death Row Records and distributed by Interscope Records.', 'images/products/thumbs/2PacEyesOnMe.jpg', 'images/products/normal/2PacEyesOnMe.jpg', 12.99, 12.99, 302, 'Hip-Hop'),
(36609, 'Fugees - The Score', 'Studio album by Fugees', 'The Score is the second and final studio album by the hip hop trio Fugees, released worldwide February 13, 1996 on Columbia Records.', 'images/products/thumbs/FugeesScore.jpg', 'images/products/normal/FugeesScore.jpg', 6.99, 5.99, 302, 'Hip-Hop'),
(36759, '50 Cent - Get Rich or Die Tryin''', 'Studio album by 50 Cent', 'Get Rich or Die Tryin'' is the debut studio album by American rapper 50 Cent. It was released on February 6, 2003, by Aftermath Entertainment, under a joint venture with Shady Records, and distributed by Interscope Records.', 'images/products/thumbs/50CentRich.jpg', 'images/products/normal/50CentRich.jpg', 7.99, 6.48, 302, 'Hip-Hop'),
(37405, 'Jay Z - The Blueprint', 'Studio album by Jay Z', 'The Blueprint is the sixth studio album by American rapper Jay-Z, released on September 11, 2001, on Roc-A-Fella Records in the United States. Its release was set a week earlier than initially planned in order to combat bootlegging.', 'images/products/thumbs/JayZBlueprint.jpg', 'images/products/normal/JayZBlueprint.jpg', 6.99, 6.99, 302, 'Hip-Hop'),
(37530, 'The Notorious B.I.G. - Ready to Die', 'Studio album by The Notorious B.I.G.', 'Ready to Die is the debut studio album by American rapper The Notorious B.I.G.; it was released on September 13, 1994, by Bad Boy Records.', 'images/products/thumbs/NotoriousBIGReadyToDie.jpg', 'images/products/normal/NotoriousBIGReadyToDie.jpg', 6.99, 6.99, 302, 'Hip-Hop'),
(37535, 'Snoop Dogg - Coolaid', 'Studio album by Snoop Dogg', 'Coolaid is the fourteenth studio album by American West Coast hip hop recording artist Snoop Dogg. It was released on July 1, 2016, by Doggystyle Records and eOne Music.', 'images/products/thumbs/SnoopDoggCoolaid.jpg', 'images/products/normal/SnoopDoggCoolaid.jpg', 7.78, 7.78, 302, 'Hip-Hop'),
(38127, 'Gwen Stefani - This Is What the Truth Feels Like', 'Studio album by Gwen Stefani', 'This Is What the Truth Feels Like is the third studio album recorded by American singer and songwriter Gwen Stefani. It was released on March 18, 2016 by Interscope Records.', 'images/products/thumbs/GwenStefaniTruth.jpg', 'images/products/normal/GwenStefaniTruth.jpg', 4.99, 3.99, 303, 'Pop'),
(38359, 'Meghan Trainor - Thank You', 'Studio album by Meghan Trainor', 'Thank You is the second major-label studio album by American singer and songwriter Meghan Trainor. The album was released exclusively on Apple Music on May 6, 2016, and was fully released on May 13, 2016, through Epic Records.', 'images/products/thumbs/MeghanTrainorThankYou.jpg',
'images/products/normal/MeghanTrainorThankYou.jpg', 6.99, 6.37, 303, 'Pop'),
(38520, 'One Direction - Made in the A.M.', 'Studio album by One Direction', 'Made in the A.M. is the fifth studio album by the English-Irish boy band One Direction, released on 13 November 2015, by Columbia Records and Syco Music.', 'images/products/thumbs/OneDirectionMade.jpg', 'images/products/normal/OneDirectionMade.jpg', 6.99, 6.99, 303, 'Pop'),
(39132, 'Zac Brown Band - Jekyll + Hyde', 'Studio album by Zac Brown Band', 'Jekyll + Hyde is the fourth major-label studio album by the Zac Brown Band. It was released on April 28, 2015. The album''s lead single, "Homegrown", was released on January 12, 2015.',

'images/products/thumbs/ZacBrownBand.jpg', 'images/products/normal/ZacBrownBand.jpg', 6.99, 6.99, 303, 'Pop'),
(39520, 'Imagine Dragons - Smoke + Mirrors', 'Studio album by Imagine Dragons', 'Smoke + Mirrors is the second studio album by American rock band Imagine Dragons. The album was recorded during 2014 at the band''s home studio in Las Vegas, Nevada.', 'images/products/thumbs/ImagineDragons.jpg', 'images/products/normal/ImagineDragons.jpg', 9.99, 9.99, 303, 'Pop'),
(39534, 'Pharrell Williams - G I R L', 'Studio album by Pharrell Williams', 'Girl is the second studio album by American recording artist and record producer Pharrell Williams. The album was released on March 3, 2014, through Williams'' label i Am Other and Columbia Records.', 'images/products/thumbs/PharrellWilliamsGIRL.jpg', 'images/products/normal/PharrellWilliamsGIRL.jpg', 8.99, 8.37, 303, 'Pop'),
(39618, 'Twenty One Pilots - Vessel', 'Album by Twenty One Pilots', 'Vessel is the third album released by the American musical duo Twenty One Pilots, which was released on January 8, 2013. It is the band''s first studio album released via Fueled by Ramen, and their major-label debut album.', 'images/products/thumbs/TwentyOnePilotsVessel.jpg', 'images/products/normal/TwentyOnePilotsVessel.jpg', 6.99, 6.99, 303, 'Pop'),
(40084, 'Usher - Looking 4 Myself', 'Studio album by Usher', 'Looking 4 Myself is the seventh studio album by American singer Usher. It was released on June 8, 2012, by RCA Records. In October 2011, it was announced that the disbandment have been occurred between Usher and the J/LaFace imprint.', 'images/products/thumbs/UsherLooking.jpg', 'images/products/normal/UsherLooking.jpg', 5.99, 5.99, 303, 'Pop'),
(40240, 'Jason Mraz - Love Is A Four Letter Word', 'Studio album by Jason Mraz', 'Love Is a Four Letter Word is the fourth studio album by the American singer-songwriter Jason Mraz, released on April 13, 2012, by Atlantic Records. "I Won''t Give Up" was released as the album''s first single on January 3, 2012.', 'images/products/thumbs/JasonMrazLove.jpg', 'images/products/normal/JasonMrazLove.jpg', 4.99, 4.99, 303, 'Pop'),
(40320, 'The Fray - Scars & Stories', 'Studio album by The Fray', 'Scars & Stories is the third studio album by American alternative rock band The Fray. It was released on February 7, 2012', 'images/products/thumbs/TheFrayScars.jpg', 'images/products/normal/TheFrayScars.jpg',
7.35, 7.35, 303, 'Pop'),
(40750, 'Green Day - Dookie', 'Studio album by Green Day', 'Dookie is the third studio album by the American punk rock band Green Day, released on February 1, 1994, through Reprise Records. It was the band''''s first collaboration with producer Rob Cavallo and its major record label debut.', 'images/products/thumbs/GreenDayDookie.jpg', 'images/products/normal/GreenDayDookie.jpg', 5.99, 5.99, 304, 'Rock'),
(40759, 'Pearl Jam - Ten', 'Studio album by Pearl Jam', 'Ten is the debut studio album by the American rock band Pearl Jam, released on August 27, 1991 through Epic Records.', 'images/products/thumbs/PearlJamTen.jpg', 'images/products/normal/PearlJamTen.jpg', 6.99,
5.49, 304, 'Rock'),
(41034, 'Alanis Morissette - Jagged Little Pill', 'Studio album by Alanis Morissette', 'Jagged Little Pill is the third studio album and international debut album by Canadian singer Alanis Morissette, first released on June 13, 1995, through Maverick Records.', 'images/products/thumbs/AlanisMorissettePill.jpg', 'images/products/normal/AlanisMorissettePill.jpg', 5.99, 5.99, 304, 'Rock'),

(41109, 'Weezer - Pinkerton', 'Studio album by Weezer', 'Pinkerton is the second studio album by the American rock band Weezer, released on September 24, 1996 on DGC Records.', 'images/products/thumbs/WeezerPinkerton.jpg', 'images/products/normal/WeezerPinkerton.jpg', 5.99, 5.99, 304, 'Rock'),
(41295, 'Muse - Absolution', 'Studio album by Muse', 'Absolution is the third studio album by English alternative rock band Muse. It was released on 15 September 2003 in Japan, 22 September 2003 in the United Kingdom by East West Records and Taste Media.', 'images/products/thumbs/MuseAbsolution.jpg', 'images/products/normal/MuseAbsolution.jpg', 6.23, 6.23, 304, 'Rock'),
(41876, 'Red Hot Chili Peppers - Stadium Arcadium', 'Studio album by Red Hot Chili Peppers', 'Stadium Arcadium is the ninth studio album by American rock band Red Hot Chili Peppers. The album was released on May 9, 2006, on Warner Bros. Records.', 'images/products/thumbs/RedHotChiliPeppersArcadium.jpg', 'images/products/normal/RedHotChiliPeppersArcadium.jpg', 5.99, 5.99, 304, 'Rock'),
(42941, 'Seether - Finding Beauty in Negative Spaces', 'Studio album by Seether', 'Finding Beauty in Negative Spaces is the fourth studio album by South African Post- grunge/Alternative metal band Seether. The album was released in South Africa and Switzerland on 19 October 2007, and released worldwide on 23 October 2007.',
'images/products/thumbs/SeetherBeauty.jpg', 'images/products/normal/SeetherBeauty.jpg', 7.99,
7.99, 304, 'Rock'),
(42994, 'Linkin Park - The Hunting Party', 'Studio album by Linkin Park', 'The Hunting Party is the sixth studio album by American rock band Linkin Park. The album, produced by band members Mike Shinoda and Brad Delson, was released by Warner Bros. Records and Machine Shop on June 13, 2014.', 'images/products/thumbs/LinkinParkHunting.jpg', 'images/products/normal/LinkinParkHunting.jpg', 6.55, 6.55, 304, 'Rock'),
(43603, 'Shinedown - Threat to Survival', 'Studio album by Shinedown', 'Threat to Survival is the fifth studio album by American rock band Shinedown. It was announced on August 7, 2015 that the album would be released on September 18, 2015. On June 29, 2015 the band released the first single "Cut the Cord".', 'images/products/thumbs/ShinedownThreat.jpg', 'images/products/normal/ShinedownThreat.jpg', 6.99, 4.99, 304, 'Rock'),
(44728, 'Finger Eleven - Life Turns Electric', 'Studio album by Finger Eleven', 'Life Turns Electric is the fifth studio album from Canadian alternative rock band Finger Eleven. It was released by Wind-up Records on October 5, 2010, was the last studio album to feature drummer Rich Beddoe, and was nominated for Rock Album of the Year at the 2011 Juno Awards.', 'images/products/thumbs/FingerElevenLife.jpg', 'images/products/normal/FingerElevenLife.jpg', 8.99, 8.99, 304, 'Rock'),
(45553, 'World of Warcraft: Legion', 'Online game', 'World of Warcraft: Legion is the sixth expansion set in the massively multiplayer online role-playing game World of Warcraft, following Warlords of Draenor. It was announced on August 6, 2015 at Gamescom 2015.', 'images/products/thumbs/WorldOfWarcraft.jpg', 'images/products/normal/WorldOfWarcraft.jpg', 89.99, 89.99, 401, 'PC'),
(45688, 'Grand Theft Auto V', 'Video game', 'Grand Theft Auto V is an open world action-adventure video game developed by Rockstar North and published by Rockstar Games.', 'images/products/thumbs/GrandTheftAuto.jpg', 'images/products/normal/GrandTheftAuto.jpg', 39.88, 39.88, 401, 'PC'),

(45708, 'Fallout 4', 'Video game', 'Fallout 4 is an action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks.', 'images/products/thumbs/Fallout4.jpg', 'images/products/normal/Fallout4.jpg', 39.99, 24.99, 401, 'PC'),
(45750, 'Minecraft', 'Video game', 'Minecraft is a sandbox video game originally created by Swedish programmer Markus "Notch" Persson and later developed and published by Mojang.', 'images/products/thumbs/Minecraft.jpg', 'images/products/normal/Minecraft.jpg', 24.88, 24.88, 401, 'PC'),
(46365, 'Half-Life 2', 'Video game', 'Half-Life 2 is a first-person shooter video game and the sequel to Half-Life. Developed by Valve Corporation, it was released on November 16, 2004, following a five-year $40 million development, during which a substantial part of the project was leaked and distributed on the Internet.', 'images/products/thumbs/HalfLife2.jpg', 'images/products/normal/HalfLife2.jpg', 9.99, 9.99, 401, 'PC'),
(46448, 'DOOM', 'Video game', 'Doom is a science fiction first-person shooter video game developed by id Software and published by Bethesda Softworks.', 'images/products/thumbs/DOOM.jpg', 'images/products/normal/DOOM.jpg', 30.79, 22.43, 401, 'PC'),
(46494, 'StarCraft II: Wings of Liberty', 'Video game', 'StarCraft II: Wings of Liberty is a military science fiction real-time strategy video game developed and released by Blizzard Entertainment for Microsoft Windows and Mac OS X.', 'images/products/thumbs/StarCraftII.jpg', 'images/products/normal/StarCraftII.jpg', 12.5, 9.99,
401, 'PC'),
(46587, 'Team Fortress 2', 'Video game', 'Team Fortress 2 is a team-based first-person shooter multiplayer video game developed and published by Valve Corporation. It is the sequel to the 1996 mod Team Fortress for Quake and its 1999 remake.', 'images/products/thumbs/TeamFortress2.jpg', 'images/products/normal/TeamFortress2.jpg', 18.79, 18.79, 401, 'PC'),
(48545, 'Diablo III', 'Video game', 'Diablo III is an action role-playing video game developed and published by Blizzard Entertainment. It is the third installment in the Diablo franchise and was released in the Americas, Europe, South Korea, and Taiwan on May 15, 2012, and Russia on June 7, 2012,[4] for Microsoft Windows and OS X.', 'images/products/thumbs/DiabloIII.jpg', 'images/products/normal/DiabloIII.jpg', 17.02, 17.02,
401, 'PC'),
(48601, 'Portal 2', 'Video game', 'Portal 2 is a 2011 first-person puzzle-platform video game developed and published by Valve Corporation. It is the sequel to Portal and was released on April 19, 2011, for Microsoft Windows, OS X, Linux, PlayStation 3, and Xbox 360.', 'images/products/thumbs/Portal2.jpg', 'images/products/normal/Portal2.jpg', 5.27, 5.27, 401, 'PC'),
(48848, 'Call of Duty: Black Ops III', 'Video game', 'Call of Duty: Black Ops III is a military science fiction first-person shooter video game, developed by Treyarch and published by Activision.', 'images/products/thumbs/CallOfDutyBlackOps.jpg', 'images/products/normal/CallOfDutyBlackOps.jpg', 39.88, 39.88, 402, 'PlayStation'),
(49554, 'Overwatch', 'Video game', 'Overwatch is a team-based multiplayer first-person shooter video game developed and published by Blizzard Entertainment. It was released in May 2016 for Microsoft Windows, PlayStation 4, and Xbox One.',

'images/products/thumbs/Overwatch.jpg', 'images/products/normal/Overwatch.jpg', 45.99, 38.48,
402, 'PlayStation'),
(49595, 'Lego Star Wars: The Force Awakens', 'Video game', 'Lego Star Wars: The Force Awakens is a Lego-themed action-adventure video game developed by TT Fusion, based on the film Star Wars: The Force Awakens. It is the fifth entry in TT Games'' Lego Star Wars series.', 'images/products/thumbs/LegoStarWars.jpg', 'images/products/normal/LegoStarWars.jpg', 37.72,
37.72, 402, 'PlayStation'),
(50589, 'The Witcher 3: Wild Hunt', 'Video game', 'The Witcher 3: Wild Hunt is an open world action role-playing video game developed by CD Projekt RED. Announced in February 2013, it was released worldwide for Microsoft Windows, PlayStation 4, and Xbox One on 19 May 2015.', 'images/products/thumbs/TheWitcher3.jpg',
'images/products/normal/TheWitcher3.jpg', 42.15, 42.15, 402, 'PlayStation'),
(50686, 'Bloodborne', 'Video game', 'Bloodborne is an action role-playing video game developed by FromSoftware and published by Sony Computer Entertainment.', 'images/products/thumbs/Bloodborne.jpg', 'images/products/normal/Bloodborne.jpg', 13.02, 8.99,
402, 'PlayStation'),
(50994, 'Horizon Zero Dawn', 'Video game', 'Horizon Zero Dawn is an upcoming action role-playing video game developed by Guerrilla Games and published by Sony Interactive Entertainment for the PlayStation 4 in 2017.', 'images/products/thumbs/HorizonZeroDawn.jpg', 'images/products/normal/HorizonZeroDawn.jpg', 59.99, 59.99, 402, 'PlayStation'),
(51194, 'Final Fantasy XV', 'Video game', 'Final Fantasy XV is an upcoming action role- playing video game being developed and published by Square Enix for the PlayStation 4 and Xbox One, and scheduled for a worldwide release on November 29, 2016.', 'images/products/thumbs/FinalFantasyXV.jpg', 'images/products/normal/FinalFantasyXV.jpg', 89.99, 89.99, 402, 'PlayStation'),
(51288, 'Homefront: The Revolution', 'Video game', 'Homefront: The Revolution is an open world first-person shooter video game developed by Dambuster Studios and published by Deep Silver for Microsoft Windows, PlayStation 4, and Xbox One, with Linux and OS X releases to follow.', 'images/products/thumbs/HomefrontTheRevolution.jpg', 'images/products/normal/HomefrontTheRevolution.jpg', 138.66, 119.88, 402, 'PlayStation'),
(51328, 'Street Fighter V', 'Video game', 'Street Fighter V is a fighting video game published by Capcom, who co-developed the game with Dimps. It is the fifth main numbered entry in the Street Fighter series.', 'images/products/thumbs/StreetFighterV.jpg', 'images/products/normal/StreetFighterV.jpg', 39.99, 39.99, 402, 'PlayStation'),
(51382, 'For Honor', 'Video game', 'For Honor is a hack and slash video game in development by Ubisoft Montreal and set to be published by Ubisoft for Microsoft Windows, PlayStation 4, and Xbox One. It was announced at the 2015 Electronic Entertainment Expo.', 'images/products/thumbs/ForHonor.jpg', 'images/products/normal/ForHonor.jpg', 59.99, 59.99,
402, 'PlayStation'),
(51438, 'Mario Kart Wii', 'Video game', 'Mario Kart Wii is a racing video game developed and published by Nintendo and released worldwide for the Wii video game console in April 2008. Mario Kart Wii was originally announced at E3 2007 by Nintendo of America president Reggie Fils-Aimé.', 'images/products/thumbs/MarioKart.jpg', 'images/products/normal/MarioKart.jpg', 26.04, 26.04, 403, 'Wii'),
(51506, 'Super Smash Bros. Brawl', 'Video game', 'Super Smash Bros. Brawl, known in Japan as Dairantō Smash Brothers X, is the third installment in the Super Smash Bros. series of

crossover fighting games, developed by an ad hoc development team consisting of Sora, Game Arts, and staff from other developers, and published by Nintendo for the Wii video game console.', 'images/products/thumbs/SuperSmashBrosBrawl.jpg', 'images/products/normal/SuperSmashBrosBrawl.jpg', 19.99, 19.99, 403, 'Wii'),
(51786, 'Wii Sports', 'Video game', 'Wii Sports is a sports game developed and published by Nintendo as a launch title for the Wii video game console.', 'images/products/thumbs/WiiSports.jpg', 'images/products/normal/WiiSports.jpg', 19.99, 17.49,
403, 'Wii'),
(52032, 'Wii Fit', 'Video game', 'Wii Fit is a video game designed by Nintendo''s Hiroshi Matsunaga for the Wii home video game console. It is an exercise game consisting of activities using the Wii Balance Board peripheral.', 'images/products/thumbs/WiiFit.jpg', 'images/products/normal/WiiFit.jpg', 20.57, 20.57, 403, 'Wii'),
(52062, 'Super Mario Galaxy', 'Video game', 'Super Mario Galaxy is a platform video game developed and published by Nintendo for the Wii. It was first released on 1 November 2007 in Japan, 12 November 2007 in North America, 16 November 2007 in Europe and on 29 November 2007 in Australia.', 'images/products/thumbs/SuperMarioGalaxy.jpg', 'images/products/normal/SuperMarioGalaxy.jpg', 9.99, 9.99, 403, 'Wii'),
(52400, 'The Legend of Zelda: Skyward Sword', 'Console game', 'The Legend of Zelda: Skyward Sword is an action-adventure game for the Wii home console, developed and published by Nintendo. The sixteenth mainline entry in the The Legend of Zelda series, it was released worldwide in November 2011.', 'images/products/thumbs/TheLegendofZelda.jpg', 'images/products/normal/TheLegendofZelda.jpg', 28.32, 25.91, 403, 'Wii'),
(52520, 'Donkey Kong Country Returns', 'Video game', 'Donkey Kong Country Returns is a 2010 side-scrolling platformer video game developed by Retro Studios and published by Nintendo for the Wii console.', 'images/products/thumbs/DonkeyKongCountryReturns.jpg', 'images/products/normal/DonkeyKongCountryReturns.jpg', 17.12, 17.12, 403, 'Wii'),
(52600, 'Animal Crossing: City Folk', 'Video game', 'Animal Crossing: City Folk, known in Europe and Oceania as Animal Crossing: Let''s Go to the City, is a 2008 life simulation video game developed and published by Nintendo for the Wii console and the third game in the Animal Crossing series.', 'images/products/thumbs/AnimalCrossingCityFolk.jpg', 'images/products/normal/AnimalCrossingCityFolk.jpg', 14.66, 13.99, 403, 'Wii'),
(53170, 'Pokémon Battle Revolution', 'Video game', 'Pokémon Battle Revolution is the first Wii incarnation of the Pokémon video game franchise. It is also the first Wii game to use the Nintendo Wi-Fi Connection in North America and Japan and the second Wii game to wirelessly interact with the Nintendo DS handheld.', 'images/products/thumbs/PokemonBattleRevolution.jpg', 'images/products/normal/PokemonBattleRevolution.jpg', 26.99, 26.99, 403, 'Wii'),
(53265, 'Kirby''s Return to Dream Land', 'Video game', 'Kirby''s Return to Dream Land, known in Japan as Hoshi no Kābī Wii and in Europe and Australia as Kirby''s Adventure Wii, is a Kirby video game and the twelfth platform installment of the series, developed by HAL Laboratory, and published by Nintendo.', 'images/products/thumbs/KirbysReturntoDreamLand.jpg', 'images/products/normal/KirbysReturntoDreamLand.jpg', 40.97, 40.97, 403, 'Wii'),
(53449, 'FIFA 16', 'Video game', 'FIFA 16 is an association football simulation video game developed by EA Canada and published by EA Sports for Microsoft Windows, PlayStation 3, PlayStation 4, Xbox 360, Xbox One, Android and iOS.',

'images/products/thumbs/FIFA16.jpg', 'images/products/normal/FIFA16.jpg', 29.99, 29.99, 404, 'XBox'),
(53516, 'Fallout: New Vegas', 'Video game', 'Fallout: New Vegas is an action role- playing video game developed by Obsidian Entertainment and published by Bethesda Softworks, as the fourth major installment of the Fallout video game series.', 'images/products/thumbs/FalloutNewVegas.jpg', 'images/products/normal/FalloutNewVegas.jpg', 14.99, 11.37, 404, 'XBox'),
(54255, 'The Elder Scrolls V: Skyrim', 'Video game', 'The Elder Scrolls V: Skyrim is an open world action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks. It is the fifth installment in The Elder Scrolls series, following The Elder Scrolls IV: Oblivion.', 'images/products/thumbs/TheElderScrollsV.jpg', 'images/products/normal/TheElderScrollsV.jpg', 14.99, 14.99, 404, 'XBox'),
(55597, 'Call of Duty: Modern Warfare 3', 'Video game', 'Call of Duty: Modern Warfare 3 is a first-person shooter video game, developed by Infinity Ward and Sledgehammer Games, with development assistance from Raven Software, and published by Activision.', 'images/products/thumbs/CallOfDutyMW3.jpg', 'images/products/normal/CallOfDutyMW3.jpg', 9.1, 9.1, 404, 'XBox'),
(55599, 'Alan Wake', 'Video game', 'Alan Wake is an action-adventure survival horror video game developed by Remedy Entertainment and published by Microsoft Studios, released for the Xbox 360 and Microsoft Windows.', 'images/products/thumbs/AlanWake.jpg', 'images/products/normal/AlanWake.jpg', 13.63, 13.63, 404, 'XBox'),
(55735, 'Plants vs. Zombies: Garden Warfare', 'Video game', 'Plants vs. Zombies: Garden Warfare is a multiplayer third-person shooter and tower defense video game. It is the third game in the Plants vs. Zombies series, developed by PopCap Games and published by Electronic Arts.', 'images/products/thumbs/PlantsvsZombiesGardenWarfare.jpg', 'images/products/normal/PlantsvsZombiesGardenWarfare.jpg', 19.99, 13.27, 404, 'XBox'),
(56089, 'Rise of the Tomb Raider', 'Video game', 'Rise of the Tomb Raider is an action- adventure video game developed by Crystal Dynamics and published by Square Enix. It is the sequel to the 2013 video game Tomb Raider, a reboot of the Tomb Raider franchise.', 'images/products/thumbs/RiseoftheTombRaider.jpg', 'images/products/normal/RiseoftheTombRaider.jpg', 24.49, 24.49, 404, 'XBox'),
(56357, 'Metal Gear Solid V: The Phantom Pain', 'Video game', 'Metal Gear Solid V: The Phantom Pain is an open world action-adventure stealth video game developed by Kojima Productions and published by Konami for Microsoft Windows, PlayStation 3, PlayStation 4, Xbox 360 and Xbox One.', 'images/products/thumbs/MetalGearSolidV.jpg', 'images/products/normal/MetalGearSolidV.jpg', 24.88, 24.88, 404, 'XBox'),
(56559, 'Injustice: Gods Among Us', 'Video game', 'Injustice: Gods Among Us is a fighting video game based upon the fictional universe of DC Comics. The game was developed by NetherRealm Studios and published by Warner Bros. Interactive Entertainment for the PlayStation 3, Xbox 360, and Wii U.', 'images/products/thumbs/Injustice.jpg', 'images/products/normal/Injustice.jpg', 15.77, 13.59, 404, 'XBox'),
(56793, 'NCAA Football 2016', 'Video Game', 'NCAA	(R) Football 16 unlocks the unpredictability and innovation of the college game. The new physics-driven animation system and a completely re-engineered spread and read option game influence the outcome of every moment allowing you to stay true to the game. Infinity Engine 2 - Experience real-time physics and the new Force Impact system as you feel every big hit, collision and tackle.',

'images/products/thumbs/NCAAFootball16.jpg', 'images/products/normal/NCAAFootball16.jpg', 39.88, 39.88, 404, 'XBox');
END